### ISSUE TITLE
Remove keep alive

### ISSUE THREAD

**Issue by cedvdb** [PixelToast/async_builder#5]
Keep alive should be the business of an upper widget.

**Comment by pingbird** [comment]
The reason it was added is because AsyncBuilder itself stores state and Flutter unfortunately makes it difficult to send keep alive notifications outside of a State. I found a bunch of instances in my team's codebase with AsyncBuilders inside of CustomScrollView, with no convenient way to tell each one to stay alive.

This feature has basically zero performance impact (some if statements in initState / dispose), and was pretty helpful in my experience, so I see no reason to remove it.
